openapi: 3.0.0
info:
  title: HireCar API
  description: HireCar API
  contact:
    email: hirecar@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /car_rentals:
    get:
      tags:
        - developers
      summary: searches retnable cars
      description: |
        search rentable cars and filter them thanks to one of those parameters
      operationId: getCarRentals
      parameters:
        - name: id
          in: query
          description: id of the car
          required: false
          style: form
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
        - name: airport_id
          in: query
          description: id of the aiport
          required: true
          style: form
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
        - name: user_id
          in: query
          description: id of the user
          required: true
          style: form
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
        - name: owner_id
          in: query
          description: id of the car's owner
          required: true
          style: form
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
        - name: airport_name
          in: query
          description: name of the  airport
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: returns car rental(s) corresponding to the parameters
          content:
            application/json:
              schema:
                type: object
                required:
                  - car_rentals
                properties:
                  car_rentals:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - start_date
                        - parking_spot
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 133
                        start_date:
                          type: string
                          format: date-time
                        end_date:
                          type: string
                          format: date-time
                        parking_spot:
                          type: object
                          required:
                            - id
                            - start_date
                            - end_date
                            - car
                            - parking_lot
                          properties:
                            id:
                              type: integer
                              format: int32
                              example: 133
                            start_date:
                              type: string
                              format: date-time
                            end_date:
                              type: string
                              format: date-time
                            car:
                              required:
                                - id
                                - model
                                - seats
                                - doors
                                - owner_id
                                - price_per_day
                                - gearbox
                                - fuel
                              type: object
                              properties:
                                id:
                                  minimum: 1
                                  type: integer
                                  format: int32
                                  example: 105
                                model:
                                  type: string
                                  example: Tesla Model S
                                seats:
                                  minimum: 1
                                  type: integer
                                  format: int32
                                  example: 5
                                doors:
                                  minimum: 1
                                  type: integer
                                  format: int32
                                  example: 5
                                owner_id:
                                  minimum: 1
                                  type: integer
                                  format: int32
                                  example: 13
                                price_per_day:
                                  minimum: 1
                                  type: number
                                  format: float
                                  example: 130.99
                                gearbox:
                                  required:
                                    - id
                                    - type
                                  type: object
                                  properties:
                                    id:
                                      minimum: 1
                                      type: integer
                                      format: int32
                                      example: 1
                                    type:
                                      type: string
                                      example: Automatique
                                fuel:
                                  required:
                                    - id
                                    - type
                                  type: object
                                  properties:
                                    id:
                                      minimum: 1
                                      type: integer
                                      format: int32
                                      example: 4
                                    type:
                                      type: string
                                      example: Électrique
                            parking_lot:
                              required:
                                - airport
                                - capacity
                                - id
                                - label
                                - lat
                                - lng
                                - price_per_day
                              type: object
                              properties:
                                id:
                                  minimum: 1
                                  type: integer
                                  format: int32
                                  example: 31
                                label:
                                  type: string
                                  example: Paris Charles de Gaulle - Terminal D1
                                lat:
                                  maximum: 90
                                  minimum: -90
                                  type: number
                                  format: float
                                  example: 49.0013
                                lng:
                                  maximum: 180
                                  minimum: -180
                                  type: number
                                  format: float
                                  example: 2.54
                                capacity:
                                  minimum: 0
                                  type: integer
                                  format: int32
                                  example: 54
                                price_per_day:
                                  minimum: 0
                                  type: number
                                  format: float
                                  example: 12.5
                                airport:
                                  required:
                                    - id
                                    - lat
                                    - lng
                                    - name
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                      format: int32
                                      example: 64
                                    name:
                                      type: string
                                      example: Paris-Charles-De-Gaulle
                                    lat:
                                      maximum: 90
                                      minimum: -90
                                      type: number
                                      format: float
                                      example: 49.0013
                                    lng:
                                      maximum: 180
                                      minimum: -180
                                      type: number
                                      format: float
                                      example: 2.54
        '400':
          description: incorrect parameters
    delete:
      tags:
        - admins
      summary: removes a car rental
      description: remove a car rental
      operationId: removeCarRentals
      parameters:
        - name: id
          in: query
          description: id of the car's rent
          required: true
          style: form
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
      responses:
        '200':
          description: deletes a car rental
        '400':
          description: invalid input
