openapi: 3.0.0
info:
  title: HireCar API
  description: HireCar API
  contact:
    email: hirecar@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  '/parking_spot_rentals/{id}':
    delete:
      tags:
        - admins
      summary: delete a parking spot rental
      description: Deletes a parking spot rental in the database
      operationId: deleteParkingSpotRental
      parameters:
        - name: id
          in: path
          description: id of the parking spot rental
          required: true
          style: simple
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
      responses:
        '200':
          description: parking spot deleted
        '400':
          description: invalid parking spot rental id
