openapi: 3.0.0
info:
  title: HireCar API
  description: HireCar API
  contact:
    email: hirecar@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  '/users/{id}':
    put:
      tags:
        - admins
      summary: update an existing user
      description: Updates an existing user in the database
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: id of the user
          required: true
          style: simple
          explode: true
          schema:
            minimum: 1
            type: integer
            format: int32
      requestBody:
        description: User to update
        content:
          application/json:
            schema:
              required:
                - firstname
                - lastname
                - email
                - phone
                - password
                - new_password
              type: object
              properties:
                firstname:
                  type: string
                  example: Marty
                lastname:
                  type: string
                  example: McFly
                email:
                  type: string
                  example: marty@delorean.com
                phone:
                  type: string
                  example: 0123456789
                password:
                  type: string
                  example: $2a$10$5p/XjRv1Kw9OIqzg4t186eV1UxpYxFTyXR4KZmABZaxV/.QlAscNe
                new_password:
                  type: string
                  example: $2a$10$5p/XjRv1Kw9OIqzg4t186eBMfo.3JXzZl4a9Fk9qZpC4MGwPzg.aq
      responses:
        '200':
          description: user updated
        '400':
          description: invalid user value
